name: CMake (CentOS rapid build on push)

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.container }} inside ${{ matrix.platform }}, Parser option ${{ matrix.xml_parser_option }}, with namespaces ${{ matrix.with_namespace}}, strict includes ${{ matrix.with_namespace }}, with examples ${{ matrix.with_examples}}, package option ${{ matrix.package_option}}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        xml_parser_option: ["-DWITH_LIBXML"]
        with_namespace: ["True"]
        strict: ["True"]
        with_examples: ["True"]
        package_option: ["-DWITH_ALL_PACKAGES=ON"]
        container: ["centos:centos7"]
    runs-on: ${{ matrix.platform }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Centos dependencies
        shell: bash
        run: |
          yum -y install swig libxml2-devel check-devel cmake

      - name: Install Centos dependencies
        shell: bash
        run: |
          yum -y update
          yum -y group install "Development Tools"

      - name: configure and build
        shell: bash
        run: |
          cd ..
          mkdir build
          cd build
          cmake ../libsbml ${{ matrix.package_option }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_CHECK=True -DWITH_JAVA=True -DWITH_CPP_NAMESPACE=${{matrix.with_namespace}} -DLIBSBML_USE_STRICT_INCLUDES=${{matrix.strict}} -DWITH_EXAMPLES=${{matrix.with_examples}}
          cmake --build . --config $BUILD_TYPE --parallel 4

      ### run tests ###
      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE
