name: Test Manylinux build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name:
      ${{ matrix.platform }}, Parser option ${{ matrix.xml_parser_option }},
      with namespaces ${{ matrix.with_namespace}}, strict includes ${{
      matrix.strict }}, with examples ${{ matrix.with_examples}}, package option
      ${{ matrix.package_option}}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        xml_parser_option: ["-DWITH_LIBXML"]
        with_namespace: ["True"]
        strict: ["True"]
        with_examples: ["True"]
        package_option: ["-DWITH_STABLE_PACKAGES=ON"]
        cpp_standard: [98]
        language_bindings: ["-DWITH_JAVA=True"]
    runs-on: ${{ matrix.platform }}
    container: quay.io/pypa/manylinux1_x86_64

    steps:
      - name: install Swig 4 from source
        run: |
          yum install -y pcre-devel
          curl -L https://sourceforge.net/projects/swig/files/swig/swig-4.0.2/swig-4.0.2.tar.gz/download > swig.tar.gz
          tar -zxvf swig.tar.gz
          cd swig-4.0.2/
          ./configure --prefix=/usr/local/swig
          make
          make install
          alias swig=/usr/local/swig/bin/swig
          swig -version

      - name: install CMake v3.12 from source
        run: |
          curl -L https://cmake.org/files/v3.12/cmake-3.12.4.tar.gz > cmake-3.12.4.tar.gz
          tar -zxvf cmake-3.12.4.tar.gz
          cd cmake-3.12.4
          ./configure --prefix=/usr/local/cmake-3.12.4
          make
          make install
          alias cmake=/usr/local/cmake-3.12.4/bin/cmake
          cmake --version

      - name: What OS is running
        run: |
          uname -a
          git --version
          git clone https://github.com/alessandrofelder/libsbml.git
          yum install -y libxml2-devel check java-devel
          alias swig=/usr/local/swig/bin/swig
          swig -version
          alias cmake=/usr/local/cmake-3.12.4/bin/cmake
          cmake --version
          mkdir build
          cd build
          cmake ../libsbml \
          -DSWIG_DIR=/usr/local/swig/ \
          -DSWIG_EXECUTABLE=/usr/local/swig/bin/swig/ \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} \
          -DWITH_CHECK=True \
          -DWITH_CPP_NAMESPACE=${{matrix.with_namespace}} \
          -DLIBSBML_USE_STRICT_INCLUDES=${{matrix.strict}} \
          -DWITH_EXAMPLES=${{matrix.with_examples}} \
          ${{matrix.package_option}} \
          ${{matrix.language_bindings}} \
          -DWITH_STATIC_RUNTIME=ON \
          -DPYTHON_USE_DYNAMIC_LOOKUP=ON
          cmake --build . --config $BUILD_TYPE

      - name: Test
        run: |
          cd build
          alias ctest=/usr/local/cmake-3.12.4/bin/ctest
          ctest -V -C $BUILD_TYPE
