name: Test Manylinux build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name:
      ${{ matrix.platform }}, Parser option ${{ matrix.xml_parser_option }},
      with namespaces ${{ matrix.with_namespace}}, strict includes ${{
      matrix.strict }}, with examples ${{ matrix.with_examples}}, package option
      ${{ matrix.package_option}}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        xml_parser_option: ["-DWITH_LIBXML"]
        with_namespace: ["True"]
        strict: ["True"]
        with_examples: ["True"]
        package_option: ["-DWITH_STABLE_PACKAGES=ON"]
        cpp_standard: [98]
        language_bindings: ["-DWITH_JAVA=True"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: dummy text file
        run: |
          mkdir install
          cd install
          echo "dummy data" >> dummy.txt
          ls -a
          cat dummy.txt

  upload:
    name: Upload test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload Centos5 binary archive
        uses: actions/upload-artifact@v2
        with:
          name:
            dummy-artefact
          path: install/*
          retention-days: 1
          if-no-files-found: error
