name: Simple persistence test

on: [push]

jobs:
  build:
    name:
      mkdir and create a file
    runs-on: ubuntu-latest
    steps:
      - name: dummy text file
        run: |
          echo "dummy data" >> dummy.txt
          ls -a
          cat dummy.txt

  upload:
    name: check whether folder and file are still there and try to upload
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: explore with ls
        run: |
          ls -a
