name: Simple persistence test

on: [push]

jobs:
  build:
    name:
      mkdir and create a file
    runs-on: ubuntu-latest
    steps:
      - name: dummy text file
        run: |
          ls -a
          mkdir install
          cd install
          echo "dummy data" >> dummy.txt
          ls -a
          cat dummy.txt

  upload:
    name: check whether folder and file are still there and try to upload
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: explore with ls
        run: |
          ls -a
          cd install
          ls -a
          cat dummy.txt

      - name: Upload folder
        uses: actions/upload-artifact@v2
        with:
          name:
            dummy-artefact
          path: install/*
          retention-days: 1
          if-no-files-found: error
